services:
  gitlab:
    image: gitlab/gitlab-ce:18.2.2-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/gitlab:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '$GITLAB_HOME/config/gitlab.rb:/etc/gitlab/gitlab.rb:ro'
    shm_size: '256m'